# fly.toml app configuration file generated for sbotgab30 on 2024-12-30T14:18:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sbotgab30'
primary_region = 'iad'
swap_size_mb = 2048

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

